name: Kernel Build CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone kernel
      run: git clone https://github.com/mvaisakh/msm-4.19 -b upstream --depth=1 ~/kernel
    - name: toolchain
      run: |
        git clone --depth=1 https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/ -b android10-gsi ~/tc/gcc/
        curl -o clang.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android11-dev/clang-r383902b.tar.gz
        mkdir -p ~/tc/clang/
        tar -xf clang.gz -C ~/tc/clang/
    - name: Set date
      id: get-date
      run: |
        ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
        echo "date=$(/bin/date -u '+%d%m%Y%I%M')" >> $GITHUB_ENV
    - name: configure
      run: |
        cd ~/kernel/
        make O=out ARCH=arm64 vendor/kona-perf_defconfig
    - name: build upstream
      run: |
        cd ~/kernel/
        make O=out ARCH=arm64 CROSS_COMPILE=~/tc/gcc/bin/aarch64-linux-android- CC=~/tc/clang/bin/clang CLANG_TRIPLE=aarch64-linux-gnu- -j$(nproc --all)
